---
- name: Git checkout
  hosts: git
  vars:
    workdir: /tmp/ex4-1
  tasks:
    - name: Git checkout
      ansible.builtin.git:
        repo: https://github.com/will421/BUT3-CloudComputing.git
        dest: "{{ workdir }}"
- name: Creation de configuration
  hosts: configuration
  vars:
    workdir: /tmp/ex4-2
  tasks:
    - name: Création dossier
      ansible.builtin.file:
        path: "{{ workdir }}/{{ env }}"
        state: directory
      when: env is defined and env | length > 0
    - name: Generation de configuration.json
      ansible.builtin.template:
        src: configuration.json.j2
        dest: "{{ workdir }}/{{ env }}/configuration.json"
      when: env is defined and env | length > 0